# Generated by Django 4.2 on 2023-05-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_author_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='color_hex_code',
            new_name='color',
        ),
    ]
